### ISSUE TITLE
Add "Max" button for xDai

### ISSUE THREAD

**Issue by rpdb-ops** [centfinance/Cent.Dex_ExchangeUI#20] opened 2021-07-02 09:01 UTC
The "Max" button doesn't appear when you try to swap from xDai but is available for all the others assets

**Comment by TheNewAutonomy** [comment] 2021-08-17 09:12
This is by design since if Max is traded then it leaves nothing for gas. I'm closing this for now but we can revisit in the future if this causes problems for users.

**Closed as completed by TheNewAutonomy** 2021-08-17 09:12 UTC
Labels: good first issue
